command: [
  "python",
  "app.py"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "xxx"
  - name: "DATABRICKS_HOST"
    value: "https://adb-984752964297111.11.azuredatabricks.net/"
  - name: "DATABRICKS_CLIENT_ID"
    value: "abc"
  - name: "DATABRICKS_CLIENT_SECRET"
    value: "xxx"
