command: [
  "python",
  "app.py"
]
env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "148ccb90800933a1"
  - name: "SERVING_ENDPOINT"
    value: "agents_retail_cpg_demo-brand_manager-cpg_sentiment_agent"
